import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 
  tutorialSidebar: [
    {
      type: 'category',
      collapsed: false,
      label: 'Get started',
      items: [
        'introduction/home',
        {
          type: 'link',
          label: 'Self-host Plane', 
          href: 'https://developers.plane.so/self-hosting/overview',
        },  
        'introduction/quickstart',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Project management 101',
      items: [
        {
          type: 'category',
          label: 'Projects',
          items: [            
          'core-concepts/projects/overview',
          'core-concepts/projects/run-project',
          ],
        },
        {
          type: 'category',
          label: 'Issues',
          items: [            
          'core-concepts/issues/overview',
          'core-concepts/issues/properties',
          'core-concepts/issues/visualise_filter',
          ],
        },
        'core-concepts/cycles',
        'core-concepts/modules',
        'core-concepts/views',
        {
          type: 'category',
          label: 'Pages',
          items: [            
          'core-concepts/pages/overview',
          'core-concepts/pages/editor-blocks',
          ],
        },
        'core-concepts/inbox',
        'core-concepts/analytics',
        'core-concepts/deploy',
        'core-concepts/power-k'
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Advanced project management',
      items: [
        'core-concepts/issues/issue-types',
        'core-concepts/issues/time-tracking'
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Workspaces and users',
      items: [
        {
          type: 'category',
          label: 'Workspaces',
          items: [            
          'core-concepts/workspaces/overview',
          'core-concepts/workspaces/members',
          ],
        },
        {
          type: 'category',
          label: 'Account',
          items: [            
          'core-concepts/account/overview',
          'core-concepts/account/settings',
          ],
        },
        'workspaces-and-users/billing-and-plans',
        'workspaces-and-users/upgrade-plan',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Importers',
      items: [
        'plane-importers/github-imp',
        'plane-importers/jira-imp',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Integrations',
      items: [
        'plane-integrations/about',
        'plane-integrations/github',
        'plane-integrations/slack',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Devices',
      items: [
        'devices/mobile',
      ],
    },
    {
      type: 'link',
      label: 'API Reference',
      href: 'https://developers.plane.so/api-reference/introduction', 
    },
    {
      type: 'link',
      label: 'Webhooks',
      href: 'https://developers.plane.so/webhooks/intro-webhooks', 
    },
  ], 
};
export default sidebars;
