name: Docs to Vector

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - docs-to-vector

env:
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect Tailscale
        # if branch is not master 
        if: ${{ github.ref_name != 'master' }}
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      
      - name: Call Webhook
        run: |
          WEBHOOK_URL=${{ secrets.VECTOR_WEBHOOK_URL }}
          if [ "${{ env.TARGET_BRANCH }}" != "master" ]; then
            WEBHOOK_URL=${{ secrets.VECTOR_WEBHOOK_URL_PREVIEW }}
          fi
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"commit_id": "${{ github.sha }}", "branch": "${{ github.ref_name }}"}' \
            ${WEBHOOK_URL}
